### ISSUE TITLE
Support DeepL free API

### ISSUE THREAD

**Issue by thebuilder** [voorhoede/datocms-plugin-translate-fields#1]
Hey great plugin, but can it add support for the free DeepL tier?
The free tier targets a different endpoint - https://api-free.deepl.com

See: https://www.deepl.com/docs-api/

**Comment by velomovies** [comment]
@thebuilder Thanks for the request! 
When Dato has updated the plugin you should be able to use version `1.1.1` with the free DeepL endpoint from the Dato plugin marketplace.
