### ISSUE TITLE
Copy and translate on Structured text can't save

### ISSUE THREAD

**Issue by PaulBouisset** [voorhoede/datocms-plugin-translate-fields#12]
First thank you a lot for the great plugin. 

I run into multiple errors on structured text when using the plugin:

- If you copy and translate a structured text containing blocks you can't save the document. It seems that this is due to the block id (I checked the console) being wrong. When you copy content with the Dato tool (not the button added by the plugin) there is no issue. Do you know how to fix this ?
- If you translate a structured text the translation only work on the text before the first block in the structured text and not all the text content

**Comment by Siilwyn** [comment]
Thank you for the feedback!
Yes structured text is hard to work with as a plugin, support is trivial atm. since it's very complex.

- We're aware of the ID duplication but don't know how to fix it (yet), any ideas welcome!
- Could you create a separate issue for this? At the moment blocks aren't translated, we'll have to investigate if this is possible to add.

**Comment by PaulBouisset** [comment]
@Siilwyn I also manage to fix the ID duplication bug but I can't make a pull request on the project
I replace the line 82 of `src/lib/translation.ts` with:
```  
value.map((item)=> item.type ==='block' ? pickBy(item,(value,key)=> !['id'].includes(key)) : item),
``
`
And importing pickBy from lodash (already in the package.json of the plugin)
```
import { pickBy } from 'lodash'
```

The trick is that blocks need to be stripped from the "id" attribute in the translated field. 

How can I propose the fix so the plugin can be updated?

**Comment by Siilwyn** [comment]
Fixed by https://github.com/voorhoede/datocms-plugin-translate-fields/pull/14

❤️ @PaulBouisset
