### ISSUE TITLE
Translate fields within modular content

### ISSUE THREAD

**Issue by earendillo** [voorhoede/datocms-plugin-translate-fields#15]
Hi, when I put "multiple-paragraph text" field straight to the model the content is translated well. But when I embed this exact field in Modular Content block it's not being translated at all.  I tried to prefill a Modular Content block with structure from the other language but it still does not work. Is it some Dato limitation?

Please let me know if any further details are necessary for investigation.

**Comment by Siilwyn** [comment]
Not sure I follow, so a `Multiple-paragraph text` field inside a block does not get translated?

**Comment by earendillo** [comment]
@Siilwyn correct

**Comment by Siilwyn** [comment]
Alright this isn't supported atm. But could be a good feature to have.

**Comment by Stackustack** [comment]
> Alright this isn't supported atm. But could be a good feature to have.

First of all, let me thank De Voorhoede team for making this awesome plugin! When it comes to this issue topic, I'm cheering to make it happen - such feature would be awesome. For our app, most of the subpages reuses modular content as such:
![image](https://user-images.githubusercontent.com/8258455/229765296-1c6ba7f4-df22-4803-b101-403d608a3f30.png)

☝️ This is just example, but you get the idea. We have the React components which supports such blocks and entire app is basically build on those. Right now automatic translations are rather insufficient as this only allows us to translate fields that are outside of modular content (and there are not used that often).

Are there any plans for developing such feature in the feature? @Siilwyn @velomovies ❤️

**Comment by Stackustack** [comment]
Hey @Siilwyn 👋 I was thinking, if you're open to outside help with that? I'd be glad to help with this feature - just let me know if no one else is working on that and and you're fine with some open-source approach and I'll start coding 👐

**Comment by Siilwyn** [comment]
Hi @Stackustack thanks for the extra information and replies!
@velomovies will be working on this issue. :)

**Comment by Stackustack** [comment]
Awesome! Thanks for your both (and all the others!) for support here, maintaining and developing this awesome plugin 🕺 Cheers!

**Comment by velomovies** [comment]
Thanks @Stackustack! You pointed me in the correct direction, but it was a bit more complicated than expected. 

Since individual fields in a modular content block don't return if the field is localized (we only get that back from the parent, the modular block itself) I now added the ability to translate (and copy) the full modular content block in https://github.com/voorhoede/datocms-plugin-translate-fields/pull/22.

**Comment by Stackustack** [comment]
@velomovies thats awesome! Thanks mate! :)

**Comment by velomovies** [comment]
As of version `1.5.0` the modular content block should be translatable. Please open a new issue when any issues arise.
