### ISSUE TITLE
Translate blocks inside a StructuredText field

### ISSUE THREAD

**Issue by christophemenager** [voorhoede/datocms-plugin-translate-fields#17]
First many thanks for the work on this plugin, it works really well for many cases and is I think, the most well developed of the marketplace for translations 🙏 

# How to reproduce?

1. Create a block with a StructuredText field
2. Create a model with an other StructudedText field that authorize to add the previous StructuredText block in its content
3. Create a record of this model and try to translate it

# Result

Only the "top" StructuredText" is translated, the block is not

<img width="906" alt="image" src="https://user-images.githubusercontent.com/17217868/211054151-c05de9c5-de62-4339-a80a-76cd65dfffe3.png">
<img width="819" alt="image" src="https://user-images.githubusercontent.com/17217868/211054187-ba9e92d5-6f30-4fb2-bb50-e2a848a344e4.png">

**Comment by velomovies** [comment]
Hi @christophemenager, 
Thanks for using the pugin! Awesome you like it so much. 

This is indeed a problem we have with all blocks inside a structured text field. Currently we only check on text blocks directly inside a structured text field and not for blocks inside the field. Structured text is a difficult one with a lot of exceptions and a complicated data structure. Blocks can have, for example, all sorts of names and data. So we need to think of a way to distinguish normal text fields with for example linked images, modelId's or json fields. 

This is a feature we want to add in the future, but feel free to open a PR.

I hope this answers you question. This unfortunately solves your problem, but I hope you understand why it's not working at the moment.

**Comment by christophemenager** [comment]
Thanks a lot @velomovies!
