### ISSUE TITLE
Provide support for DeepL Glossaries

### ISSUE THREAD

**Issue by nibtime** [voorhoede/datocms-plugin-translate-fields#19]
First things first: thank you for developing this amazing and useful plugin! It works awesome for our use-case.

Today I created an interface for native speakers to maintain a glossary for auto-translations for 6 language pairs with `en` as source.

When I finished, I realized the plugin currently has no support to make use of the glossaries. To use a glossary, you have to pass a `glossary_id` param when translating text (see https://www.deepl.com/docs-api/translate-text/translate-text/).

From my current understanding of DatoCMS plugins (very basic), this could be realized by adding an optional 'Glossary' field to plugin configuration, when DeepL is selected as translation service. Here it would be important to use the Glossary `name` instead of `glossary_id`, as glossaries are immutable and for every update you need to delete old glossaries by name and language pair and creating a new one which gets a new `glossary_id` (see https://www.deepl.com/docs-api/glossaries/)

To create/update glossaries I use a pipedream workflow which connects Google Sheets data, with a cron trigger for daily updates.
I created a "Create/Update glossaries" action, that internally receives all existing glossaries, then deletes all existing glossaries that match the input name and language pair and then creates a new one with new `glossary_id` for the input name and language pair with the associated range from Google Sheet.

<details>
<summary>Google Sheets interface</summary>
<img width="466" alt="2023-02-24 21_51_27-DeepL API - Brave" src="https://user-images.githubusercontent.com/52962482/221289186-a80ce3b6-f4f0-44dc-8e0e-62e94f05d342.png">

</details>

<details>
<summary>Pipedream workflow</summary>
<img width="1188" alt="2023-02-24 21_42_07-Update Bulletin Glossary (en-es) - Pipedream - Brave" src="https://user-images.githubusercontent.com/52962482/221287749-401bf061-280e-4bab-97b4-b6a0800d6879.png">

</details>

What the plugin would have to do, would be considering a configured glossary (global and field level) by name before making the translation request.

1. retrieve all glossaries (https://www.deepl.com/docs-api/glossaries/list-glossaries/)
2. select `glossary_id` of first that matches `name`, `source_lang` and `target_lang`. `name` comes from Plugin configuration
3. pass `glossary_id` to translation request (https://www.deepl.com/docs-api/translate-text/translate-text/)

I'd be willing to implement this and send a PR if you like the plugin to support this, I might need some guidance regarding DatoCMS plugin development though.

**Comment by Siilwyn** [comment]
@nibtime thank you for creating this issue!

Since the plugin does/can not keep state fetching all glossaries would happen every time a translation is fetched, I do wonder if that's a good idea. Do you think it will feel slow, and/or will hit rate limits?

Alternatively somebody could want to use glossaries that do not automatically update, as in using specific IDs. Do you think that's a valid use-case?
Going this route would mean we need a list of glossaries in the config with an: ID, source lang and target lang.

Let me know what you think, once we agree a PR is more than welcome as we don't have time in the coming month to work on this. The plugin is mostly React code and testing the plugin can be done by [pointing Dato to localhost](https://www.datocms.com/docs/plugin-sdk/build-your-first-plugin#configure-your-plugin), a bit more is explained in the contributing.md file.

**Comment by nibtime** [comment]
@Siilwyn thank you for considering this and your feedback!

You are right, that fetching the glossary ids by name before every translation request could be a bad idea, as it would double the number of API requests, for basically nothing.

I think using a list with (id, source lang, target lang) would be a better option for plugin configuration then. 

The workflow that updates the glossaries from Google Sheet outputs the newly created glossary ids. I could add an additional step, that updates plugin configuration with new (id, source lang, target lang) via DatoCMS API. So that means if you need glossaries to be maintained regularly, you'd have to consider updating DatoCMS plugin configuration via backend logic by yourself. If a glossary really is immutable, which could also be a valid use-case, then it is fine anyway.

I also think it's a bit of flawed API design by DeepL that doesn't consider enough that glossaries can be living documents updated by native speakers. This would be much easier if translation requests supported passing glossaries by name. 

I think I will give it a try and go for a PR with this approach then.

**Comment by Siilwyn** [comment]
Thank you!

> DeepL that doesn't consider enough that glossaries can be living documents updated by native speakers.
Exactly, I'm not familiar with DeepL but that seems either an oversight or intentional decision.

**Comment by Stackustack** [comment]
@nibtime any update on that? Or you abandoned the idea of coding this feature? My team is looking forward for that feature and Im guessing we're not the only one :D

**Comment by velomovies** [comment]
Hi @nibtime and @Stackustack, 
I have added the ability to add a glossary id when Deepl is selected as a translation service. I have no experience with Deepl but from the documentation and the explanation above I think I have added it correctly. 

I will update the plugin to version `1.9.0`. If this doesn't work as intended please open a new issue.
