### ISSUE TITLE
Translate from default locale

### ISSUE THREAD

**Issue by PrimozRome** [voorhoede/datocms-plugin-translate-fields#21]
Hi. How so that sometimes the button "Translate from default locale" is available and sometimes not?

This would be very useful as sometimes you don't want to translate "to all locale" but just translate a certain locale from default locale.

Thanks, P.

**Comment by velomovies** [comment]
Hi @PrimozRome,

The `Translate from default locale` button should only show when the field is empty. If that seems not the case with your Plugin instance we need a bit more details about how you set up the plugin. 

Let us know if the button indeed renders when a field is empty or if there seems another problem!
