### ISSUE TITLE
Translate SEO fiels issue with empty value

### ISSUE THREAD

**Issue by PrimozRome** [voorhoede/datocms-plugin-translate-fields#24]
I'm really happy that the plugin now supports translation on SEO fields.

There is one issue though. If the SEO title or META is empty and you translate it to locales it will insert "null" to the filed that is empty. I think it would be much better if the empty value stays empty after translation...

**Comment by velomovies** [comment]
Thanks for raising this issue. You can update to version `1.6.1` where this should be fixed.
