### ISSUE TITLE
Data not serialized

### ISSUE THREAD

**Issue by RomainFrancony** [voorhoede/datocms-plugin-translate-fields#26]
When translating a "complex" field, either SEO or Strutured Text, the plugin does not serialize the content. Thus sending `[object Object]` to the Deepl Free API.

![capture](https://github.com/voorhoede/datocms-plugin-translate-fields/assets/22396965/6bccd4a1-f32d-4634-828f-33b4e9c434d5)

Tested with the latest version of the plugin (1.6.1) and with the Deepl Free API, don't known if other services are also impacted.

**Comment by RomainFrancony** [comment]
After some digging, I found the problem:

https://github.com/voorhoede/datocms-plugin-translate-fields/blob/c5415848efe438b94a900f02032ce317483d0239/src/entrypoints/FieldAddon/FieldAddon.tsx#L79

This should be `appearance` not `appeareance`. This makes the `translationFormat` `undefined` and therefore translate using the default method for simple input field.

**Comment by velomovies** [comment]
Thanks for raising this issue! This will be fixed in a next version
