### ISSUE TITLE
Unable to install the plugin.

### ISSUE THREAD

**Issue by alexflm** [voorhoede/datocms-plugin-translate-fields#43]
Hello!

I tried to add the translate plugin from the datocms marketplace, but after clicking on the install button, datocms opens with the project, but nothing happens, the plugin is not installed. Plugins from other developers install without problems.

I tried it in Safari and Chrome browsers.

**Comment by velomovies** [comment]
Hi @alexflm, thanks for the raising this issue. This looks like an DatoCMS issue, which we can't solve. All plugins on the plugin page work correctly, but I see that if you click on "view all" and go to the next page URL parameters disappear which result in not be able to add the plugin correctly.

Can you try to go to this URL where [projectname] should be your datocms project name? `https://www.datocms.com/marketplace/plugins/i/datocms-plugin-translate-fields?projectDomain=[projectname].admin.datocms.com&projectName=[projectname]`

If that works I think we should raise an issue with the DatoCMS developers

**Comment by velomovies** [comment]
I will close this since it should be fixed (if it has not already been fixed) by Dato (see https://github.com/datocms/plugins/issues/100)
