### ISSUE TITLE
Open AI all gpt models give 404 error

### ISSUE THREAD

**Issue by marcmartinkettal** [voorhoede/datocms-plugin-translate-fields#47]
Hello!

When I try to translate something with all the models of chatgpt returns: OpenAI returned status 404

Thanks for your work

**Comment by marcelofinamorvieira** [comment]
@marcmartinkettal Whoops, i had forgotten to change the parameter to the new one: https://github.com/voorhoede/datocms-plugin-translate-fields/pull/49 
Sorry about that! 😅
