### ISSUE TITLE
Setting exceptions for certain fields

### ISSUE THREAD

**Issue by tolchai** [voorhoede/datocms-plugin-translate-fields#52]
Hi,

I am using modular approach for our websites, so each page is built from Blocks via Modular Content. 

Problem with this is that auto apply (set for Modular Content) translate everything in the modules, including strings set to "Select input" in field's presentation settings. We are using those for example for selection of background color of the module, with three options (black, white, blue etc), so in this case the selected value (for example "black") is translated to "schwarz" in german, removing the actual functionality. 

Is there a way around this? Maybe setting some exception for this kind of content (either on per-field base, or on text fields with "Select input" presentation in general). 

Thanks!

**Comment by Siilwyn** [comment]
Sounds like a good feature, this issue is also mentioned in https://github.com/voorhoede/datocms-plugin-translate-fields/issues/51

> Some read-only fields are sometimes also translated, which is very odd

PR is welcome :sparkles:

**Comment by velomovies** [comment]
We have added it in version `v1.12.0`. When Dato picked up the new version you will be able to exclude certain fields from translating
