### ISSUE TITLE
Double translate button

### ISSUE THREAD

**Issue by PrimozRome** [voorhoede/datocms-plugin-translate-fields#9]
Sometimes two translate buttons show under the filed to where plugin is applied... See the screenshot.

<img width="1407" alt="Screenshot 2022-08-11 at 14 01 31" src="https://user-images.githubusercontent.com/1180467/184129240-f0ec2d3b-40e2-4adb-bb75-93f52f3068c4.png">

I could not find pattern, but it happens on multiple places, kind of random.

**Comment by Siilwyn** [comment]
Good catch, PR welcome!

**Comment by Arash217** [comment]
@PrimozRome for me this bug occurred when I happened to install the plugin both via the marketplace as well as a private plugin. Was this also your case? If not could you elaborate more. What version of the plugin do you use?

**Comment by Siilwyn** [comment]
Waiting for author reply.
